group:
  repos: |
    ODINN-SciML/Huginn.jl
    ODINN-SciML/Muninn.jl
    ODINN-SciML/ODINN.jl
  files: 
    - source: environment.yml
      dest: environment.yml
    - source: .gitignore
      dest: .gitignore
    - source: .github/workflows/CI.yml
      dest: .github/workflows/CI.yml
