name: oggm_env_20240917_ssl

channels:
  - conda-forge

dependencies:
  # Base language runtimes
  - python<3.12

  # Python packages
  - bottleneck
  - cartopy
  - configobj
  - dask
  - gdal
  - geopandas
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - motionless
  - netcdf4
  - numpy<2.0
  - numpydoc
  - openssl=3.0
  - pandas
  - Pillow
  - pip
  - pyproj
  - pytables
  - pytest
  - rasterio
  - rioxarray
  - salem
  - seaborn
  - shapely
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  
  # Packages installed through pip
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl
    - git+https://github.com/OGGM/massbalance-sandbox
    - oggm
    - certifi
